// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kurs_PW.Models
{
    public partial class AccountStatus
    {
        public AccountStatus()
        {
            Users = new HashSet<Users>();
        }

        public int StatusId { get; set; }
        public string StatusName { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}