// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kurs_PW.Models
{
    public partial class Characters
    {
        public int CharacterId { get; set; }
        public string Nickname { get; set; }
        public int? ClassId { get; set; }
        public string Heaven { get; set; }
        public int? Lvl { get; set; }
        public int? Rebirths { get; set; }
        public string Guild { get; set; }
        public string Spouse { get; set; }
        public int? Reputation { get; set; }
        public string Status { get; set; }
        public string Title { get; set; }
        public int? LifeForce { get; set; }
        public int? MagicalEnergy { get; set; }
        public int? Spirit { get; set; }
        public byte[] Image { get; set; }
        public int? PerformancePoints { get; set; }
        public int? Endurance { get; set; }
        public int? Intelligence { get; set; }
        public int? Power { get; set; }
        public int? Agility { get; set; }
        public int? PhysicalAttack { get; set; }
        public int? MagicAttack { get; set; }
        public string CriticalStrikeChance { get; set; }
        public string AttackSpeed { get; set; }
        public int? Accuracy { get; set; }
        public int? IndicatorAttack { get; set; }
        public int? FightingSpirit { get; set; }
        public int? Stealth { get; set; }
        public int? MonsterDamage { get; set; }
        public int? PhysicalPunching { get; set; }
        public int? PhysicalProtection { get; set; }
        public int? MagicProtection { get; set; }
        public string CriticalDamage { get; set; }
        public string Speed { get; set; }
        public int? Evasion { get; set; }
        public int? IndicatorProtection { get; set; }
        public int? Fortitude { get; set; }
        public int? Detection { get; set; }
        public int? MonsterProtection { get; set; }
        public int? MagicPunching { get; set; }
        public int? UserId { get; set; }
        public int? FractionId { get; set; }
        public int? SoulChannelsId { get; set; }

        public virtual Classes Class { get; set; }
        public virtual Fractions Fraction { get; set; }
        public virtual SoulChannels SoulChannels { get; set; }
        public virtual Users User { get; set; }
    }
}