// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kurs_PW.Models
{
    public partial class Classes
    {
        public Classes()
        {
            Characters = new HashSet<Characters>();
        }

        public int ClassId { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Characters> Characters { get; set; }
    }
}