// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kurs_PW.Models
{
    public partial class Fractions
    {
        public Fractions()
        {
            Characters = new HashSet<Characters>();
        }

        public int FractionId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Quartermasters { get; set; }
        public string Token { get; set; }

        public virtual ICollection<Characters> Characters { get; set; }
    }
}