// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kurs_PW.Models
{
    public partial class Message
    {
        public int MessageId { get; set; }
        public int? SenderId { get; set; }
        public int? RecipientId { get; set; }
        public string Text { get; set; }

        public virtual Users Recipient { get; set; }
        public virtual Users Sender { get; set; }
    }
}